// Generated by scripts/generate-xml-cardinality.mjs. Do not edit.
//
// Which elements repeat, per resource type. XML cannot express cardinality, so
// the parser needs this to know that a lone <jurisdiction> is a one-item list
// while a lone <description> is not.
//
// The empty key holds a resource's own repeating elements; every other key is a
// backbone element, holding the repeating elements inside it.

export const REPEATING_BY_RESOURCE: Readonly<
  Record<string, Readonly<Record<string, readonly string[]>>>
> = {
  "Account": {
    "": [
      "coverage",
      "guarantor",
      "identifier",
      "subject"
    ]
  },
  "ActivityDefinition": {
    "": [
      "author",
      "bodySite",
      "contact",
      "dosage",
      "dynamicValue",
      "editor",
      "endorser",
      "identifier",
      "jurisdiction",
      "library",
      "observationRequirement",
      "observationResultRequirement",
      "participant",
      "relatedArtifact",
      "reviewer",
      "specimenRequirement",
      "topic",
      "useContext"
    ]
  },
  "AdverseEvent": {
    "suspectEntity": [
      "causality"
    ],
    "": [
      "category",
      "contributor",
      "referenceDocument",
      "resultingCondition",
      "study",
      "subjectMedicalHistory",
      "suspectEntity"
    ]
  },
  "AllergyIntolerance": {
    "reaction": [
      "manifestation",
      "note"
    ],
    "": [
      "category",
      "identifier",
      "note",
      "reaction"
    ]
  },
  "Appointment": {
    "participant": [
      "type"
    ],
    "": [
      "basedOn",
      "identifier",
      "participant",
      "reasonCode",
      "reasonReference",
      "requestedPeriod",
      "serviceCategory",
      "serviceType",
      "slot",
      "specialty",
      "supportingInformation"
    ]
  },
  "AppointmentResponse": {
    "": [
      "identifier",
      "participantType"
    ]
  },
  "AuditEvent": {
    "agent": [
      "policy",
      "purposeOfUse",
      "role"
    ],
    "source": [
      "type"
    ],
    "entity": [
      "detail",
      "securityLabel"
    ],
    "": [
      "agent",
      "entity",
      "purposeOfEvent",
      "subtype"
    ]
  },
  "Basic": {
    "": [
      "identifier"
    ]
  },
  "BiologicallyDerivedProduct": {
    "": [
      "identifier",
      "parent",
      "processing",
      "request",
      "storage"
    ]
  },
  "BodyStructure": {
    "": [
      "identifier",
      "image",
      "locationQualifier"
    ]
  },
  "Bundle": {
    "entry": [
      "link"
    ],
    "": [
      "entry",
      "link"
    ]
  },
  "CapabilityStatement": {
    "rest": [
      "compartment",
      "interaction",
      "operation",
      "resource",
      "searchParam"
    ],
    "messaging": [
      "endpoint",
      "supportedMessage"
    ],
    "": [
      "contact",
      "document",
      "format",
      "implementationGuide",
      "imports",
      "instantiates",
      "jurisdiction",
      "messaging",
      "patchFormat",
      "rest",
      "useContext"
    ]
  },
  "CarePlan": {
    "activity": [
      "outcomeCodeableConcept",
      "outcomeReference",
      "progress"
    ],
    "": [
      "activity",
      "addresses",
      "basedOn",
      "careTeam",
      "category",
      "contributor",
      "goal",
      "identifier",
      "instantiatesCanonical",
      "instantiatesUri",
      "note",
      "partOf",
      "replaces",
      "supportingInfo"
    ]
  },
  "CareTeam": {
    "participant": [
      "role"
    ],
    "": [
      "category",
      "identifier",
      "managingOrganization",
      "note",
      "participant",
      "reasonCode",
      "reasonReference",
      "telecom"
    ]
  },
  "CatalogEntry": {
    "": [
      "additionalCharacteristic",
      "additionalClassification",
      "additionalIdentifier",
      "classification",
      "identifier",
      "relatedEntry"
    ]
  },
  "ChargeItem": {
    "": [
      "account",
      "bodysite",
      "definitionCanonical",
      "definitionUri",
      "identifier",
      "note",
      "partOf",
      "performer",
      "reason",
      "service",
      "supportingInformation"
    ]
  },
  "ChargeItemDefinition": {
    "propertyGroup": [
      "applicability",
      "priceComponent"
    ],
    "": [
      "applicability",
      "contact",
      "derivedFromUri",
      "identifier",
      "instance",
      "jurisdiction",
      "partOf",
      "propertyGroup",
      "replaces",
      "useContext"
    ]
  },
  "Claim": {
    "diagnosis": [
      "type"
    ],
    "procedure": [
      "type",
      "udi"
    ],
    "insurance": [
      "preAuthRef"
    ],
    "item": [
      "careTeamSequence",
      "detail",
      "diagnosisSequence",
      "encounter",
      "informationSequence",
      "modifier",
      "procedureSequence",
      "programCode",
      "subSite",
      "udi"
    ],
    "": [
      "careTeam",
      "diagnosis",
      "identifier",
      "insurance",
      "item",
      "procedure",
      "related",
      "supportingInfo"
    ]
  },
  "ClaimResponse": {
    "item": [
      "adjudication",
      "detail",
      "noteNumber"
    ],
    "addItem": [
      "adjudication",
      "detail",
      "detailSequence",
      "itemSequence",
      "modifier",
      "noteNumber",
      "programCode",
      "provider",
      "subSite",
      "subdetailSequence"
    ],
    "": [
      "addItem",
      "adjudication",
      "communicationRequest",
      "error",
      "identifier",
      "insurance",
      "item",
      "processNote",
      "total"
    ]
  },
  "ClinicalImpression": {
    "investigation": [
      "item"
    ],
    "": [
      "finding",
      "identifier",
      "investigation",
      "note",
      "problem",
      "prognosisCodeableConcept",
      "prognosisReference",
      "protocol",
      "supportingInfo"
    ]
  },
  "CodeSystem": {
    "filter": [
      "operator"
    ],
    "concept": [
      "concept",
      "designation",
      "property"
    ],
    "": [
      "concept",
      "contact",
      "filter",
      "identifier",
      "jurisdiction",
      "property",
      "useContext"
    ]
  },
  "Communication": {
    "": [
      "about",
      "basedOn",
      "category",
      "identifier",
      "inResponseTo",
      "instantiatesCanonical",
      "instantiatesUri",
      "medium",
      "note",
      "partOf",
      "payload",
      "reasonCode",
      "reasonReference",
      "recipient"
    ]
  },
  "CommunicationRequest": {
    "": [
      "about",
      "basedOn",
      "category",
      "identifier",
      "medium",
      "note",
      "payload",
      "reasonCode",
      "reasonReference",
      "recipient",
      "replaces"
    ]
  },
  "CompartmentDefinition": {
    "resource": [
      "param"
    ],
    "": [
      "contact",
      "resource",
      "useContext"
    ]
  },
  "Composition": {
    "event": [
      "code",
      "detail"
    ],
    "section": [
      "author",
      "entry",
      "section"
    ],
    "": [
      "attester",
      "author",
      "category",
      "event",
      "relatesTo",
      "section"
    ]
  },
  "ConceptMap": {
    "group": [
      "element"
    ],
    "": [
      "contact",
      "group",
      "jurisdiction",
      "useContext"
    ]
  },
  "Condition": {
    "stage": [
      "assessment"
    ],
    "evidence": [
      "code",
      "detail"
    ],
    "": [
      "bodySite",
      "category",
      "evidence",
      "identifier",
      "note",
      "stage"
    ]
  },
  "Consent": {
    "provision": [
      "action",
      "actor",
      "class",
      "code",
      "data",
      "provision",
      "purpose",
      "securityLabel"
    ],
    "": [
      "category",
      "identifier",
      "organization",
      "performer",
      "policy",
      "verification"
    ]
  },
  "Contract": {
    "term": [
      "action",
      "asset",
      "group",
      "securityLabel"
    ],
    "signer": [
      "signature"
    ],
    "": [
      "alias",
      "authority",
      "domain",
      "friendly",
      "identifier",
      "legal",
      "relevantHistory",
      "rule",
      "signer",
      "site",
      "subType",
      "subject",
      "supportingInfo",
      "term"
    ]
  },
  "Coverage": {
    "costToBeneficiary": [
      "exception"
    ],
    "": [
      "class",
      "contract",
      "costToBeneficiary",
      "identifier",
      "payor"
    ]
  },
  "CoverageEligibilityRequest": {
    "item": [
      "detail",
      "diagnosis",
      "modifier",
      "supportingInfoSequence"
    ],
    "": [
      "identifier",
      "insurance",
      "item",
      "purpose",
      "supportingInfo"
    ]
  },
  "CoverageEligibilityResponse": {
    "insurance": [
      "item"
    ],
    "": [
      "error",
      "identifier",
      "insurance",
      "purpose"
    ]
  },
  "DetectedIssue": {
    "evidence": [
      "code",
      "detail"
    ],
    "": [
      "evidence",
      "identifier",
      "implicated",
      "mitigation"
    ]
  },
  "Device": {
    "property": [
      "valueCode",
      "valueQuantity"
    ],
    "": [
      "contact",
      "deviceName",
      "identifier",
      "note",
      "property",
      "safety",
      "specialization",
      "statusReason",
      "udiCarrier",
      "version"
    ]
  },
  "DeviceDefinition": {
    "capability": [
      "description"
    ],
    "property": [
      "valueCode",
      "valueQuantity"
    ],
    "": [
      "capability",
      "contact",
      "deviceName",
      "identifier",
      "languageCode",
      "material",
      "note",
      "property",
      "safety",
      "shelfLifeStorage",
      "specialization",
      "udiDeviceIdentifier",
      "version"
    ]
  },
  "DeviceMetric": {
    "": [
      "calibration",
      "identifier"
    ]
  },
  "DeviceRequest": {
    "": [
      "basedOn",
      "identifier",
      "instantiatesCanonical",
      "instantiatesUri",
      "insurance",
      "note",
      "parameter",
      "priorRequest",
      "reasonCode",
      "reasonReference",
      "relevantHistory",
      "supportingInfo"
    ]
  },
  "DeviceUseStatement": {
    "": [
      "basedOn",
      "derivedFrom",
      "identifier",
      "note",
      "reasonCode",
      "reasonReference"
    ]
  },
  "DiagnosticReport": {
    "": [
      "basedOn",
      "category",
      "conclusionCode",
      "identifier",
      "imagingStudy",
      "media",
      "performer",
      "presentedForm",
      "result",
      "resultsInterpreter",
      "specimen"
    ]
  },
  "DocumentManifest": {
    "": [
      "author",
      "content",
      "identifier",
      "recipient",
      "related"
    ]
  },
  "DocumentReference": {
    "context": [
      "encounter",
      "event",
      "related"
    ],
    "": [
      "author",
      "category",
      "content",
      "identifier",
      "relatesTo",
      "securityLabel"
    ]
  },
  "EffectEvidenceSynthesis": {
    "effectEstimate": [
      "precisionEstimate"
    ],
    "certainty": [
      "certaintySubcomponent",
      "note",
      "rating"
    ],
    "": [
      "author",
      "certainty",
      "contact",
      "editor",
      "effectEstimate",
      "endorser",
      "identifier",
      "jurisdiction",
      "note",
      "relatedArtifact",
      "resultsByExposure",
      "reviewer",
      "topic",
      "useContext"
    ]
  },
  "Encounter": {
    "participant": [
      "type"
    ],
    "hospitalization": [
      "dietPreference",
      "specialArrangement",
      "specialCourtesy"
    ],
    "": [
      "account",
      "appointment",
      "basedOn",
      "classHistory",
      "diagnosis",
      "episodeOfCare",
      "identifier",
      "location",
      "participant",
      "reasonCode",
      "reasonReference",
      "statusHistory",
      "type"
    ]
  },
  "Endpoint": {
    "": [
      "contact",
      "header",
      "identifier",
      "payloadMimeType",
      "payloadType"
    ]
  },
  "EnrollmentRequest": {
    "": [
      "identifier"
    ]
  },
  "EnrollmentResponse": {
    "": [
      "identifier"
    ]
  },
  "EpisodeOfCare": {
    "": [
      "account",
      "diagnosis",
      "identifier",
      "referralRequest",
      "statusHistory",
      "team",
      "type"
    ]
  },
  "EventDefinition": {
    "": [
      "author",
      "contact",
      "editor",
      "endorser",
      "identifier",
      "jurisdiction",
      "relatedArtifact",
      "reviewer",
      "topic",
      "trigger",
      "useContext"
    ]
  },
  "Evidence": {
    "": [
      "author",
      "contact",
      "editor",
      "endorser",
      "exposureVariant",
      "identifier",
      "jurisdiction",
      "note",
      "outcome",
      "relatedArtifact",
      "reviewer",
      "topic",
      "useContext"
    ]
  },
  "EvidenceVariable": {
    "characteristic": [
      "usageContext"
    ],
    "": [
      "author",
      "characteristic",
      "contact",
      "editor",
      "endorser",
      "identifier",
      "jurisdiction",
      "note",
      "relatedArtifact",
      "reviewer",
      "topic",
      "useContext"
    ]
  },
  "ExampleScenario": {
    "instance": [
      "containedInstance",
      "version"
    ],
    "process": [
      "step"
    ],
    "": [
      "actor",
      "contact",
      "identifier",
      "instance",
      "jurisdiction",
      "process",
      "useContext",
      "workflow"
    ]
  },
  "ExplanationOfBenefit": {
    "diagnosis": [
      "type"
    ],
    "procedure": [
      "type",
      "udi"
    ],
    "insurance": [
      "preAuthRef"
    ],
    "item": [
      "adjudication",
      "careTeamSequence",
      "detail",
      "diagnosisSequence",
      "encounter",
      "informationSequence",
      "modifier",
      "noteNumber",
      "procedureSequence",
      "programCode",
      "subSite",
      "udi"
    ],
    "addItem": [
      "adjudication",
      "detail",
      "detailSequence",
      "itemSequence",
      "modifier",
      "noteNumber",
      "programCode",
      "provider",
      "subDetailSequence",
      "subSite"
    ],
    "benefitBalance": [
      "financial"
    ],
    "": [
      "addItem",
      "adjudication",
      "benefitBalance",
      "careTeam",
      "diagnosis",
      "identifier",
      "insurance",
      "item",
      "preAuthRef",
      "preAuthRefPeriod",
      "procedure",
      "processNote",
      "related",
      "supportingInfo",
      "total"
    ]
  },
  "FamilyMemberHistory": {
    "condition": [
      "note"
    ],
    "": [
      "condition",
      "identifier",
      "instantiatesCanonical",
      "instantiatesUri",
      "note",
      "reasonCode",
      "reasonReference"
    ]
  },
  "Flag": {
    "": [
      "category",
      "identifier"
    ]
  },
  "Goal": {
    "": [
      "addresses",
      "category",
      "identifier",
      "note",
      "outcomeCode",
      "outcomeReference",
      "target"
    ]
  },
  "GraphDefinition": {
    "link": [
      "target"
    ],
    "": [
      "contact",
      "jurisdiction",
      "link",
      "useContext"
    ]
  },
  "Group": {
    "": [
      "characteristic",
      "identifier",
      "member"
    ]
  },
  "GuidanceResponse": {
    "": [
      "dataRequirement",
      "evaluationMessage",
      "identifier",
      "note",
      "reasonCode",
      "reasonReference"
    ]
  },
  "HealthcareService": {
    "availableTime": [
      "daysOfWeek"
    ],
    "": [
      "availableTime",
      "category",
      "characteristic",
      "communication",
      "coverageArea",
      "eligibility",
      "endpoint",
      "identifier",
      "location",
      "notAvailable",
      "program",
      "referralMethod",
      "serviceProvisionCode",
      "specialty",
      "telecom",
      "type"
    ]
  },
  "ImagingStudy": {
    "series": [
      "endpoint",
      "instance",
      "performer",
      "specimen"
    ],
    "": [
      "basedOn",
      "endpoint",
      "identifier",
      "interpreter",
      "modality",
      "note",
      "procedureCode",
      "reasonCode",
      "reasonReference",
      "series"
    ]
  },
  "Immunization": {
    "protocolApplied": [
      "targetDisease"
    ],
    "": [
      "education",
      "identifier",
      "note",
      "performer",
      "programEligibility",
      "protocolApplied",
      "reaction",
      "reasonCode",
      "reasonReference",
      "subpotentReason"
    ]
  },
  "ImmunizationEvaluation": {
    "": [
      "doseStatusReason",
      "identifier"
    ]
  },
  "ImmunizationRecommendation": {
    "recommendation": [
      "contraindicatedVaccineCode",
      "dateCriterion",
      "forecastReason",
      "supportingImmunization",
      "supportingPatientInformation",
      "vaccineCode"
    ],
    "": [
      "identifier",
      "recommendation"
    ]
  },
  "ImplementationGuide": {
    "definition": [
      "grouping",
      "parameter",
      "resource",
      "template"
    ],
    "manifest": [
      "image",
      "other",
      "page",
      "resource"
    ],
    "": [
      "contact",
      "dependsOn",
      "fhirVersion",
      "global",
      "jurisdiction",
      "useContext"
    ]
  },
  "InsurancePlan": {
    "contact": [
      "telecom"
    ],
    "coverage": [
      "benefit",
      "network"
    ],
    "plan": [
      "coverageArea",
      "generalCost",
      "identifier",
      "network",
      "specificCost"
    ],
    "": [
      "alias",
      "contact",
      "coverage",
      "coverageArea",
      "endpoint",
      "identifier",
      "network",
      "plan",
      "type"
    ]
  },
  "Invoice": {
    "lineItem": [
      "priceComponent"
    ],
    "": [
      "identifier",
      "lineItem",
      "note",
      "participant",
      "totalPriceComponent"
    ]
  },
  "Library": {
    "": [
      "author",
      "contact",
      "content",
      "dataRequirement",
      "editor",
      "endorser",
      "identifier",
      "jurisdiction",
      "parameter",
      "relatedArtifact",
      "reviewer",
      "topic",
      "useContext"
    ]
  },
  "Linkage": {
    "": [
      "item"
    ]
  },
  "List": {
    "": [
      "entry",
      "identifier",
      "note"
    ]
  },
  "Location": {
    "hoursOfOperation": [
      "daysOfWeek"
    ],
    "": [
      "alias",
      "endpoint",
      "hoursOfOperation",
      "identifier",
      "telecom",
      "type"
    ]
  },
  "Measure": {
    "group": [
      "population",
      "stratifier"
    ],
    "supplementalData": [
      "usage"
    ],
    "": [
      "author",
      "contact",
      "definition",
      "editor",
      "endorser",
      "group",
      "identifier",
      "jurisdiction",
      "library",
      "relatedArtifact",
      "reviewer",
      "supplementalData",
      "topic",
      "type",
      "useContext"
    ]
  },
  "MeasureReport": {
    "group": [
      "population",
      "stratifier"
    ],
    "": [
      "evaluatedResource",
      "group",
      "identifier"
    ]
  },
  "Media": {
    "": [
      "basedOn",
      "identifier",
      "note",
      "partOf",
      "reasonCode"
    ]
  },
  "Medication": {
    "": [
      "identifier",
      "ingredient"
    ]
  },
  "MedicationAdministration": {
    "": [
      "device",
      "eventHistory",
      "identifier",
      "instantiates",
      "note",
      "partOf",
      "performer",
      "reasonCode",
      "reasonReference",
      "statusReason",
      "supportingInformation"
    ]
  },
  "MedicationDispense": {
    "substitution": [
      "reason",
      "responsibleParty"
    ],
    "": [
      "authorizingPrescription",
      "detectedIssue",
      "dosageInstruction",
      "eventHistory",
      "identifier",
      "note",
      "partOf",
      "performer",
      "receiver",
      "supportingInformation"
    ]
  },
  "MedicationKnowledge": {
    "relatedMedicationKnowledge": [
      "reference"
    ],
    "administrationGuidelines": [
      "dosage",
      "patientCharacteristics"
    ],
    "medicineClassification": [
      "classification"
    ],
    "regulatory": [
      "schedule",
      "substitution"
    ],
    "kinetics": [
      "areaUnderCurve",
      "lethalDose50"
    ],
    "": [
      "administrationGuidelines",
      "associatedMedication",
      "contraindication",
      "cost",
      "drugCharacteristic",
      "ingredient",
      "intendedRoute",
      "kinetics",
      "medicineClassification",
      "monitoringProgram",
      "monograph",
      "productType",
      "regulatory",
      "relatedMedicationKnowledge",
      "synonym"
    ]
  },
  "MedicationRequest": {
    "": [
      "basedOn",
      "category",
      "detectedIssue",
      "dosageInstruction",
      "eventHistory",
      "identifier",
      "instantiatesCanonical",
      "instantiatesUri",
      "insurance",
      "note",
      "reasonCode",
      "reasonReference",
      "supportingInformation"
    ]
  },
  "MedicationStatement": {
    "": [
      "basedOn",
      "derivedFrom",
      "dosage",
      "identifier",
      "note",
      "partOf",
      "reasonCode",
      "reasonReference",
      "statusReason"
    ]
  },
  "MedicinalProduct": {
    "name": [
      "countryLanguage",
      "namePart"
    ],
    "manufacturingBusinessOperation": [
      "manufacturer"
    ],
    "specialDesignation": [
      "identifier"
    ],
    "": [
      "attachedDocument",
      "clinicalTrial",
      "contact",
      "crossReference",
      "identifier",
      "manufacturingBusinessOperation",
      "marketingStatus",
      "masterFile",
      "name",
      "packagedMedicinalProduct",
      "pharmaceuticalProduct",
      "productClassification",
      "specialDesignation",
      "specialMeasures"
    ]
  },
  "MedicinalProductAuthorization": {
    "jurisdictionalAuthorization": [
      "identifier",
      "jurisdiction"
    ],
    "procedure": [
      "application"
    ],
    "": [
      "country",
      "identifier",
      "jurisdiction",
      "jurisdictionalAuthorization"
    ]
  },
  "MedicinalProductContraindication": {
    "": [
      "comorbidity",
      "otherTherapy",
      "population",
      "subject",
      "therapeuticIndication"
    ]
  },
  "MedicinalProductIndication": {
    "": [
      "comorbidity",
      "otherTherapy",
      "population",
      "subject",
      "undesirableEffect"
    ]
  },
  "MedicinalProductIngredient": {
    "specifiedSubstance": [
      "strength"
    ],
    "substance": [
      "strength"
    ],
    "": [
      "manufacturer",
      "specifiedSubstance"
    ]
  },
  "MedicinalProductInteraction": {
    "": [
      "interactant",
      "subject"
    ]
  },
  "MedicinalProductManufactured": {
    "": [
      "ingredient",
      "manufacturer",
      "otherCharacteristics"
    ]
  },
  "MedicinalProductPackaged": {
    "packageItem": [
      "alternateMaterial",
      "device",
      "identifier",
      "manufacturedItem",
      "manufacturer",
      "material",
      "otherCharacteristics",
      "packageItem",
      "shelfLifeStorage"
    ],
    "": [
      "batchIdentifier",
      "identifier",
      "manufacturer",
      "marketingStatus",
      "packageItem",
      "subject"
    ]
  },
  "MedicinalProductPharmaceutical": {
    "routeOfAdministration": [
      "targetSpecies"
    ],
    "": [
      "characteristics",
      "device",
      "identifier",
      "ingredient",
      "routeOfAdministration"
    ]
  },
  "MedicinalProductUndesirableEffect": {
    "": [
      "population",
      "subject"
    ]
  },
  "MessageDefinition": {
    "": [
      "allowedResponse",
      "contact",
      "focus",
      "graph",
      "identifier",
      "jurisdiction",
      "parent",
      "replaces",
      "useContext"
    ]
  },
  "MessageHeader": {
    "": [
      "destination",
      "focus"
    ]
  },
  "MolecularSequence": {
    "": [
      "identifier",
      "pointer",
      "quality",
      "repository",
      "structureVariant",
      "variant"
    ]
  },
  "NamingSystem": {
    "": [
      "contact",
      "jurisdiction",
      "uniqueId",
      "useContext"
    ]
  },
  "NutritionOrder": {
    "oralDiet": [
      "fluidConsistencyType",
      "nutrient",
      "schedule",
      "texture",
      "type"
    ],
    "supplement": [
      "schedule"
    ],
    "enteralFormula": [
      "administration"
    ],
    "": [
      "allergyIntolerance",
      "excludeFoodModifier",
      "foodPreferenceModifier",
      "identifier",
      "instantiates",
      "instantiatesCanonical",
      "instantiatesUri",
      "note",
      "supplement"
    ]
  },
  "Observation": {
    "referenceRange": [
      "appliesTo"
    ],
    "component": [
      "interpretation",
      "referenceRange"
    ],
    "": [
      "basedOn",
      "category",
      "component",
      "derivedFrom",
      "focus",
      "hasMember",
      "identifier",
      "interpretation",
      "note",
      "partOf",
      "performer",
      "referenceRange"
    ]
  },
  "ObservationDefinition": {
    "qualifiedInterval": [
      "appliesTo"
    ],
    "": [
      "category",
      "identifier",
      "permittedDataType",
      "qualifiedInterval"
    ]
  },
  "OperationDefinition": {
    "parameter": [
      "part",
      "referencedFrom",
      "targetProfile"
    ],
    "overload": [
      "parameterName"
    ],
    "": [
      "contact",
      "jurisdiction",
      "overload",
      "parameter",
      "resource",
      "useContext"
    ]
  },
  "OperationOutcome": {
    "issue": [
      "expression",
      "location"
    ],
    "": [
      "issue"
    ]
  },
  "Organization": {
    "contact": [
      "telecom"
    ],
    "": [
      "address",
      "alias",
      "contact",
      "endpoint",
      "identifier",
      "telecom",
      "type"
    ]
  },
  "OrganizationAffiliation": {
    "": [
      "code",
      "endpoint",
      "healthcareService",
      "identifier",
      "location",
      "network",
      "specialty",
      "telecom"
    ]
  },
  "Parameters": {
    "parameter": [
      "part"
    ],
    "": [
      "parameter"
    ]
  },
  "Patient": {
    "contact": [
      "relationship",
      "telecom"
    ],
    "": [
      "address",
      "communication",
      "contact",
      "generalPractitioner",
      "identifier",
      "link",
      "name",
      "photo",
      "telecom"
    ]
  },
  "PaymentNotice": {
    "": [
      "identifier"
    ]
  },
  "PaymentReconciliation": {
    "": [
      "detail",
      "identifier",
      "processNote"
    ]
  },
  "Person": {
    "": [
      "address",
      "identifier",
      "link",
      "name",
      "telecom"
    ]
  },
  "PlanDefinition": {
    "goal": [
      "addresses",
      "documentation",
      "target"
    ],
    "action": [
      "action",
      "code",
      "condition",
      "documentation",
      "dynamicValue",
      "goalId",
      "input",
      "output",
      "participant",
      "reason",
      "relatedAction",
      "trigger"
    ],
    "": [
      "action",
      "author",
      "contact",
      "editor",
      "endorser",
      "goal",
      "identifier",
      "jurisdiction",
      "library",
      "relatedArtifact",
      "reviewer",
      "topic",
      "useContext"
    ]
  },
  "Practitioner": {
    "qualification": [
      "identifier"
    ],
    "": [
      "address",
      "communication",
      "identifier",
      "name",
      "photo",
      "qualification",
      "telecom"
    ]
  },
  "PractitionerRole": {
    "availableTime": [
      "daysOfWeek"
    ],
    "": [
      "availableTime",
      "code",
      "endpoint",
      "healthcareService",
      "identifier",
      "location",
      "notAvailable",
      "specialty",
      "telecom"
    ]
  },
  "Procedure": {
    "": [
      "basedOn",
      "bodySite",
      "complication",
      "complicationDetail",
      "focalDevice",
      "followUp",
      "identifier",
      "instantiatesCanonical",
      "instantiatesUri",
      "note",
      "partOf",
      "performer",
      "reasonCode",
      "reasonReference",
      "report",
      "usedCode",
      "usedReference"
    ]
  },
  "Provenance": {
    "agent": [
      "role"
    ],
    "entity": [
      "agent"
    ],
    "": [
      "agent",
      "entity",
      "policy",
      "reason",
      "signature",
      "target"
    ]
  },
  "Questionnaire": {
    "item": [
      "answerOption",
      "code",
      "enableWhen",
      "initial",
      "item"
    ],
    "": [
      "code",
      "contact",
      "derivedFrom",
      "identifier",
      "item",
      "jurisdiction",
      "subjectType",
      "useContext"
    ]
  },
  "QuestionnaireResponse": {
    "item": [
      "answer",
      "item"
    ],
    "": [
      "basedOn",
      "item",
      "partOf"
    ]
  },
  "RelatedPerson": {
    "": [
      "address",
      "communication",
      "identifier",
      "name",
      "photo",
      "relationship",
      "telecom"
    ]
  },
  "RequestGroup": {
    "action": [
      "action",
      "code",
      "condition",
      "documentation",
      "participant",
      "relatedAction"
    ],
    "": [
      "action",
      "basedOn",
      "identifier",
      "instantiatesCanonical",
      "instantiatesUri",
      "note",
      "reasonCode",
      "reasonReference",
      "replaces"
    ]
  },
  "ResearchDefinition": {
    "": [
      "author",
      "comment",
      "contact",
      "editor",
      "endorser",
      "identifier",
      "jurisdiction",
      "library",
      "relatedArtifact",
      "reviewer",
      "topic",
      "useContext"
    ]
  },
  "ResearchElementDefinition": {
    "characteristic": [
      "usageContext"
    ],
    "": [
      "author",
      "characteristic",
      "comment",
      "contact",
      "editor",
      "endorser",
      "identifier",
      "jurisdiction",
      "library",
      "relatedArtifact",
      "reviewer",
      "topic",
      "useContext"
    ]
  },
  "ResearchStudy": {
    "": [
      "arm",
      "category",
      "condition",
      "contact",
      "enrollment",
      "focus",
      "identifier",
      "keyword",
      "location",
      "note",
      "objective",
      "partOf",
      "protocol",
      "relatedArtifact",
      "site"
    ]
  },
  "ResearchSubject": {
    "": [
      "identifier"
    ]
  },
  "RiskAssessment": {
    "": [
      "basis",
      "identifier",
      "note",
      "prediction",
      "reasonCode",
      "reasonReference"
    ]
  },
  "RiskEvidenceSynthesis": {
    "riskEstimate": [
      "precisionEstimate"
    ],
    "certainty": [
      "certaintySubcomponent",
      "note",
      "rating"
    ],
    "": [
      "author",
      "certainty",
      "contact",
      "editor",
      "endorser",
      "identifier",
      "jurisdiction",
      "note",
      "relatedArtifact",
      "reviewer",
      "topic",
      "useContext"
    ]
  },
  "Schedule": {
    "": [
      "actor",
      "identifier",
      "serviceCategory",
      "serviceType",
      "specialty"
    ]
  },
  "SearchParameter": {
    "": [
      "base",
      "chain",
      "comparator",
      "component",
      "contact",
      "jurisdiction",
      "modifier",
      "target",
      "useContext"
    ]
  },
  "ServiceRequest": {
    "": [
      "basedOn",
      "bodySite",
      "category",
      "identifier",
      "instantiatesCanonical",
      "instantiatesUri",
      "insurance",
      "locationCode",
      "locationReference",
      "note",
      "orderDetail",
      "performer",
      "reasonCode",
      "reasonReference",
      "relevantHistory",
      "replaces",
      "specimen",
      "supportingInfo"
    ]
  },
  "Slot": {
    "": [
      "identifier",
      "serviceCategory",
      "serviceType",
      "specialty"
    ]
  },
  "Specimen": {
    "processing": [
      "additive"
    ],
    "container": [
      "identifier"
    ],
    "": [
      "condition",
      "container",
      "identifier",
      "note",
      "parent",
      "processing",
      "request"
    ]
  },
  "SpecimenDefinition": {
    "typeTested": [
      "handling",
      "rejectionCriterion"
    ],
    "": [
      "collection",
      "patientPreparation",
      "typeTested"
    ]
  },
  "StructureDefinition": {
    "snapshot": [
      "element"
    ],
    "differential": [
      "element"
    ],
    "": [
      "contact",
      "context",
      "contextInvariant",
      "identifier",
      "jurisdiction",
      "keyword",
      "mapping",
      "useContext"
    ]
  },
  "StructureMap": {
    "group": [
      "input",
      "rule"
    ],
    "": [
      "contact",
      "group",
      "identifier",
      "import",
      "jurisdiction",
      "structure",
      "useContext"
    ]
  },
  "Subscription": {
    "channel": [
      "header"
    ],
    "": [
      "contact"
    ]
  },
  "Substance": {
    "": [
      "category",
      "identifier",
      "ingredient",
      "instance"
    ]
  },
  "SubstanceNucleicAcid": {
    "subunit": [
      "linkage",
      "sugar"
    ],
    "": [
      "subunit"
    ]
  },
  "SubstancePolymer": {
    "monomerSet": [
      "startingMaterial"
    ],
    "repeat": [
      "repeatUnit"
    ],
    "": [
      "copolymerConnectivity",
      "modification",
      "monomerSet",
      "repeat"
    ]
  },
  "SubstanceProtein": {
    "": [
      "disulfideLinkage",
      "subunit"
    ]
  },
  "SubstanceReferenceInformation": {
    "gene": [
      "source"
    ],
    "geneElement": [
      "source"
    ],
    "classification": [
      "source",
      "subtype"
    ],
    "target": [
      "source"
    ],
    "": [
      "classification",
      "gene",
      "geneElement",
      "target"
    ]
  },
  "SubstanceSourceMaterial": {
    "organism": [
      "author"
    ],
    "": [
      "countryOfOrigin",
      "fractionDescription",
      "geographicalLocation",
      "parentSubstanceId",
      "parentSubstanceName",
      "partDescription"
    ]
  },
  "SubstanceSpecification": {
    "structure": [
      "isotope",
      "representation",
      "source"
    ],
    "code": [
      "source"
    ],
    "name": [
      "domain",
      "jurisdiction",
      "official",
      "source",
      "synonym",
      "translation"
    ],
    "relationship": [
      "source"
    ],
    "": [
      "code",
      "moiety",
      "molecularWeight",
      "name",
      "property",
      "relationship",
      "source"
    ]
  },
  "SupplyDelivery": {
    "": [
      "basedOn",
      "identifier",
      "partOf",
      "receiver"
    ]
  },
  "SupplyRequest": {
    "": [
      "identifier",
      "parameter",
      "reasonCode",
      "reasonReference",
      "supplier"
    ]
  },
  "Task": {
    "restriction": [
      "recipient"
    ],
    "": [
      "basedOn",
      "identifier",
      "input",
      "insurance",
      "note",
      "output",
      "partOf",
      "performerType",
      "relevantHistory"
    ]
  },
  "TerminologyCapabilities": {
    "codeSystem": [
      "version"
    ],
    "expansion": [
      "parameter"
    ],
    "": [
      "codeSystem",
      "contact",
      "jurisdiction",
      "useContext"
    ]
  },
  "TestReport": {
    "setup": [
      "action"
    ],
    "test": [
      "action"
    ],
    "teardown": [
      "action"
    ],
    "": [
      "participant",
      "test"
    ]
  },
  "TestScript": {
    "metadata": [
      "capability",
      "link"
    ],
    "setup": [
      "action"
    ],
    "test": [
      "action"
    ],
    "teardown": [
      "action"
    ],
    "": [
      "contact",
      "destination",
      "fixture",
      "jurisdiction",
      "origin",
      "profile",
      "test",
      "useContext",
      "variable"
    ]
  },
  "ValueSet": {
    "compose": [
      "exclude",
      "include"
    ],
    "expansion": [
      "contains",
      "parameter"
    ],
    "": [
      "contact",
      "identifier",
      "jurisdiction",
      "useContext"
    ]
  },
  "VerificationResult": {
    "primarySource": [
      "communicationMethod",
      "pushTypeAvailable",
      "type"
    ],
    "": [
      "primarySource",
      "target",
      "targetLocation",
      "validationProcess",
      "validator"
    ]
  },
  "VisionPrescription": {
    "lensSpecification": [
      "note",
      "prism"
    ],
    "": [
      "identifier",
      "lensSpecification"
    ]
  }
};

/** Inherited from Resource and DomainResource, so repeating on everything. */
export const REPEATING_COMMON: readonly string[] = ["contained","extension","modifierExtension"];

/**
 * Where FHIR XML nests a resource one level deeper than JSON does, as
 * `resourceType.parent.element` with an empty parent for the top level.
 *
 * Only the positions R4 actually types as `Resource`. Matching the element
 * name alone destroys `Procedure.outcome`, which is a CodeableConcept.
 */
export const RESOURCE_CONTAINER_AT: readonly string[] = ["Bundle.entry.resource","Parameters.parameter.resource"];
