import type { ResourceShape } from '../types';
import {
  address,
  annotation,
  choice,
  concept,
  contact,
  group,
  identifier,
  join,
  name,
  period,
  primitive,
  reference,
  statusDisplay,
  textOf,
} from './helpers';

/**
 * Resources outside the Clinical section that clinical payloads almost always
 * reference. Kept separate so the clinical coverage stays easy to audit.
 */
export const ADMINISTRATIVE_SHAPE: Readonly<Record<string, ResourceShape>> = {
  Patient: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      name: name(),
      telecom: contact(),
      gender: primitive(),
      birthDate: primitive(),
      deceased: choice(),
      address: address(),
      maritalStatus: concept(),
      multipleBirth: choice(),
      generalPractitioner: reference(true),
      managingOrganization: reference(),
      contact: group({
        relationship: concept(true),
        name: name(false),
        telecom: contact(),
        address: address(false),
        gender: primitive(),
        organization: reference(),
        period: period(),
      }),
      communication: group({ language: concept(), preferred: primitive() }),
      link: group({ other: reference(), type: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'birthDate')),
  },

  Practitioner: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      name: name(),
      telecom: contact(),
      address: address(),
      gender: primitive(),
      birthDate: primitive(),
      communication: concept(true),
      qualification: group({
        identifier: identifier(),
        code: concept(),
        period: period(),
        issuer: reference(),
      }),
    },
    display: (fields) => textOf(fields, 'name'),
  },

  PractitionerRole: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      period: period(),
      practitioner: reference(),
      organization: reference(),
      code: concept(true),
      specialty: concept(true),
      location: reference(true),
      healthcareService: reference(true),
      telecom: contact(),
    },
    display: (fields) => join(textOf(fields, 'code'), textOf(fields, 'specialty')),
  },

  Organization: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      type: concept(true),
      name: primitive(),
      alias: primitive(true),
      telecom: contact(),
      address: address(),
      partOf: reference(),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'type')),
  },

  Location: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      name: primitive(),
      alias: primitive(true),
      description: primitive(),
      mode: primitive(),
      type: concept(true),
      telecom: contact(),
      address: address(false),
      physicalType: concept(),
      managingOrganization: reference(),
      partOf: reference(),
    },
    display: statusDisplay('name'),
  },

  Encounter: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      class: concept(),
      type: concept(true),
      serviceType: concept(),
      priority: concept(),
      subject: reference(),
      basedOn: reference(true),
      participant: group({
        type: concept(true),
        period: period(),
        individual: reference(),
        actor: reference(),
      }),
      appointment: reference(true),
      period: period(),
      length: primitive(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      diagnosis: group({ condition: reference(), use: concept(), rank: primitive() }),
      account: reference(true),
      serviceProvider: reference(),
      partOf: reference(),
      location: group({ location: reference(), status: primitive(), period: period() }),
    },
    display: (fields) => join(textOf(fields, 'class'), textOf(fields, 'period')),
  },

  EpisodeOfCare: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      type: concept(true),
      patient: reference(),
      managingOrganization: reference(),
      period: period(),
      referralRequest: reference(true),
      careManager: reference(),
      team: reference(true),
      account: reference(true),
      diagnosis: group({ condition: reference(), role: concept(), rank: primitive() }),
    },
    display: statusDisplay('type'),
  },

  DocumentReference: {
    fields: {
      identifier: identifier(),
      masterIdentifier: identifier(false),
      status: primitive(),
      docStatus: primitive(),
      type: concept(),
      category: concept(true),
      subject: reference(),
      date: primitive(),
      author: reference(true),
      authenticator: reference(),
      custodian: reference(),
      description: primitive(),
      securityLabel: concept(true),
      content: group({ attachment: primitive(), format: concept() }),
      context: group(
        {
          encounter: reference(true),
          event: concept(true),
          period: period(),
          facilityType: concept(),
          practiceSetting: concept(),
        },
        false,
      ),
    },
    display: statusDisplay('type'),
  },

  RelatedPerson: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      patient: reference(),
      relationship: concept(true),
      name: name(),
      telecom: contact(),
      gender: primitive(),
      birthDate: primitive(),
      address: address(),
      period: period(),
      communication: group({ language: concept(), preferred: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'relationship')),
  },

  Device: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      manufacturer: primitive(),
      manufactureDate: primitive(),
      expirationDate: primitive(),
      lotNumber: primitive(),
      serialNumber: primitive(),
      modelNumber: primitive(),
      type: concept(),
      patient: reference(),
      owner: reference(),
      contact: contact(),
      location: reference(),
      note: annotation(),
    },
    display: statusDisplay('type'),
  },
};
