import type { ResourceShape } from '../types';
import {
  address,
  annotation,
  choice,
  concept,
  contact,
  group,
  identifier,
  join,
  name,
  period,
  primitive,
  quantity,
  ratio,
  reference,
  statusDisplay,
  textOf,
} from './helpers';

/**
 * Every resource in the Base section of the FHIR resource list — Individuals,
 * Entities, Workflow, and Management.
 *
 * R4 element names lead, since R4 is the canonical target. Resources the
 * current build added after R4 are declared conservatively: an element that
 * turns out to be wrong or missing is read generically and reported in
 * `unmapped`, so the cost is a less curated reading, never lost data.
 */
export const BASE_SHAPE: Readonly<Record<string, ResourceShape>> = {
  // -------------------------------------------------------- Individuals ----
  Patient: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      name: name(),
      telecom: contact(),
      gender: primitive(),
      birthDate: primitive(),
      deceased: choice(),
      address: address(),
      maritalStatus: concept(),
      multipleBirth: choice(),
      generalPractitioner: reference(true),
      managingOrganization: reference(),
      contact: group({
        relationship: concept(true),
        name: name(false),
        telecom: contact(),
        address: address(false),
        gender: primitive(),
        organization: reference(),
        period: period(),
      }),
      communication: group({ language: concept(), preferred: primitive() }),
      link: group({ other: reference(), type: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'birthDate')),
  },

  Practitioner: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      name: name(),
      telecom: contact(),
      address: address(),
      gender: primitive(),
      birthDate: primitive(),
      communication: concept(true),
      qualification: group({
        identifier: identifier(),
        code: concept(),
        period: period(),
        issuer: reference(),
      }),
    },
    display: (fields) => textOf(fields, 'name'),
  },

  PractitionerRole: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      period: period(),
      practitioner: reference(),
      organization: reference(),
      code: concept(true),
      specialty: concept(true),
      location: reference(true),
      healthcareService: reference(true),
      telecom: contact(),
      availabilityExceptions: primitive(),
      endpoint: reference(true),
    },
    display: (fields) => join(textOf(fields, 'code'), textOf(fields, 'specialty')),
  },

  RelatedPerson: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      patient: reference(),
      relationship: concept(true),
      name: name(),
      telecom: contact(),
      gender: primitive(),
      birthDate: primitive(),
      address: address(),
      period: period(),
      communication: group({ language: concept(), preferred: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'relationship')),
  },

  Person: {
    fields: {
      identifier: identifier(),
      name: name(),
      telecom: contact(),
      gender: primitive(),
      birthDate: primitive(),
      address: address(),
      managingOrganization: reference(),
      active: primitive(),
      link: group({ target: reference(), assurance: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'birthDate')),
  },

  Group: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      type: primitive(),
      actual: primitive(),
      code: concept(),
      name: primitive(),
      quantity: primitive(),
      managingEntity: reference(),
      characteristic: group({
        code: concept(),
        value: choice(),
        exclude: primitive(),
        period: period(),
      }),
      member: group({ entity: reference(), period: period(), inactive: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'type')),
  },

  // ------------------------------------------------------- Entities #1 ----
  Organization: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      type: concept(true),
      name: primitive(),
      alias: primitive(true),
      telecom: contact(),
      address: address(),
      partOf: reference(),
      endpoint: reference(true),
      contact: group({
        purpose: concept(),
        name: name(false),
        telecom: contact(),
        address: address(false),
      }),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'type')),
  },

  OrganizationAffiliation: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      period: period(),
      organization: reference(),
      participatingOrganization: reference(),
      network: reference(true),
      code: concept(true),
      specialty: concept(true),
      location: reference(true),
      healthcareService: reference(true),
      telecom: contact(),
      endpoint: reference(true),
    },
    display: (fields) => join(textOf(fields, 'code'), textOf(fields, 'specialty')),
  },

  HealthcareService: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      providedBy: reference(),
      category: concept(true),
      type: concept(true),
      specialty: concept(true),
      location: reference(true),
      name: primitive(),
      comment: primitive(),
      extraDetails: primitive(),
      telecom: contact(),
      coverageArea: reference(true),
      serviceProvisionCode: concept(true),
      program: concept(true),
      characteristic: concept(true),
      communication: concept(true),
      referralMethod: concept(true),
      appointmentRequired: primitive(),
      availabilityExceptions: primitive(),
      endpoint: reference(true),
    },
    display: (fields) => join(textOf(fields, 'name'), textOf(fields, 'type')),
  },

  Endpoint: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      connectionType: concept(),
      name: primitive(),
      managingOrganization: reference(),
      contact: contact(),
      period: period(),
      payloadType: concept(true),
      payloadMimeType: primitive(true),
      address: primitive(),
      header: primitive(true),
    },
    display: statusDisplay('name'),
  },

  Location: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      operationalStatus: concept(),
      name: primitive(),
      alias: primitive(true),
      description: primitive(),
      mode: primitive(),
      type: concept(true),
      telecom: contact(),
      address: address(false),
      physicalType: concept(),
      managingOrganization: reference(),
      partOf: reference(),
      availabilityExceptions: primitive(),
      endpoint: reference(true),
    },
    display: statusDisplay('name'),
  },

  // ------------------------------------------------------- Entities #2 ----
  Substance: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      category: concept(true),
      code: concept(),
      description: primitive(),
      instance: group({ identifier: identifier(false), expiry: primitive(), quantity: quantity() }),
      ingredient: group({
        quantity: ratio(),
        substanceCodeableConcept: concept(),
        substanceReference: reference(),
      }),
    },
    display: statusDisplay('code'),
  },

  BiologicallyDerivedProduct: {
    fields: {
      identifier: identifier(),
      productCategory: primitive(),
      productCode: concept(),
      status: primitive(),
      request: reference(true),
      quantity: primitive(),
      parent: reference(true),
      collection: group(
        { collector: reference(), source: reference(), collected: choice() },
        false,
      ),
      manipulation: group({ description: primitive(), time: choice() }, false),
    },
    display: statusDisplay('productCode'),
  },

  Device: {
    fields: {
      identifier: identifier(),
      definition: reference(),
      status: primitive(),
      statusReason: concept(true),
      manufacturer: primitive(),
      manufactureDate: primitive(),
      expirationDate: primitive(),
      lotNumber: primitive(),
      serialNumber: primitive(),
      modelNumber: primitive(),
      partNumber: primitive(),
      type: concept(),
      patient: reference(),
      owner: reference(),
      contact: contact(),
      location: reference(),
      url: primitive(),
      safety: concept(true),
      parent: reference(),
      note: annotation(),
      deviceName: group({ name: primitive(), type: primitive() }),
      version: group({ type: concept(), value: primitive() }),
    },
    display: statusDisplay('type'),
  },

  DeviceDefinition: {
    fields: {
      identifier: identifier(),
      modelNumber: primitive(),
      type: concept(),
      safety: concept(true),
      manufacturer: choice(),
      owner: reference(),
      contact: contact(),
      url: primitive(),
      note: annotation(),
      quantity: quantity(),
      parentDevice: reference(),
      deviceName: group({ name: primitive(), type: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'type'), textOf(fields, 'modelNumber')),
  },

  DeviceMetric: {
    fields: {
      identifier: identifier(),
      type: concept(),
      unit: concept(),
      source: reference(),
      parent: reference(),
      operationalStatus: primitive(),
      color: primitive(),
      category: primitive(),
      calibration: group({ type: primitive(), state: primitive(), time: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'type'), textOf(fields, 'category')),
  },

  /** R5 and later. */
  NutritionProduct: {
    fields: {
      code: concept(),
      status: primitive(),
      category: concept(true),
      manufacturer: reference(true),
      note: annotation(),
    },
    display: statusDisplay('code'),
  },

  /** R6 draft. Declared conservatively; anything missed is read generically. */
  DeviceAlert: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      condition: concept(),
      priority: primitive(),
      type: concept(),
      subject: reference(),
      device: reference(),
    },
    display: statusDisplay('type'),
  },

  // ----------------------------------------------------------- Workflow ----
  Task: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      statusReason: concept(),
      businessStatus: concept(),
      intent: primitive(),
      priority: primitive(),
      code: concept(),
      description: primitive(),
      focus: reference(),
      for: reference(),
      encounter: reference(),
      executionPeriod: period(),
      authoredOn: primitive(),
      lastModified: primitive(),
      requester: reference(),
      owner: reference(),
      location: reference(),
      reasonCode: concept(),
      reasonReference: reference(),
      note: annotation(),
      restriction: group({ repetitions: primitive(), period: period() }, false),
    },
    display: statusDisplay('code'),
  },

  Appointment: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      cancelationReason: concept(),
      serviceCategory: concept(true),
      serviceType: concept(true),
      specialty: concept(true),
      appointmentType: concept(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      priority: primitive(),
      description: primitive(),
      start: primitive(),
      end: primitive(),
      minutesDuration: primitive(),
      slot: reference(true),
      created: primitive(),
      comment: primitive(),
      patientInstruction: primitive(),
      participant: group({
        type: concept(true),
        actor: reference(),
        required: primitive(),
        status: primitive(),
        period: period(),
      }),
    },
    display: (fields) => join(textOf(fields, 'description'), textOf(fields, 'start')),
  },

  AppointmentResponse: {
    fields: {
      identifier: identifier(),
      appointment: reference(),
      start: primitive(),
      end: primitive(),
      participantType: concept(true),
      actor: reference(),
      participantStatus: primitive(),
      comment: primitive(),
    },
    display: (fields) => join(textOf(fields, 'participantStatus'), textOf(fields, 'start')),
  },

  Schedule: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      serviceCategory: concept(true),
      serviceType: concept(true),
      specialty: concept(true),
      actor: reference(true),
      planningHorizon: period(),
      comment: primitive(),
    },
    display: (fields) => join(textOf(fields, 'serviceType'), textOf(fields, 'planningHorizon')),
  },

  Slot: {
    fields: {
      identifier: identifier(),
      serviceCategory: concept(true),
      serviceType: concept(true),
      specialty: concept(true),
      appointmentType: concept(),
      schedule: reference(),
      status: primitive(),
      start: primitive(),
      end: primitive(),
      overbooked: primitive(),
      comment: primitive(),
    },
    display: (fields) => join(textOf(fields, 'status'), textOf(fields, 'start')),
  },

  // --------------------------------------------------------- Management ----
  Encounter: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      class: concept(),
      type: concept(true),
      serviceType: concept(),
      priority: concept(),
      subject: reference(),
      basedOn: reference(true),
      participant: group({
        type: concept(true),
        period: period(),
        individual: reference(),
        actor: reference(),
      }),
      appointment: reference(true),
      period: period(),
      length: primitive(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      diagnosis: group({ condition: reference(), use: concept(), rank: primitive() }),
      account: reference(true),
      serviceProvider: reference(),
      partOf: reference(),
      location: group({ location: reference(), status: primitive(), period: period() }),
      hospitalization: group(
        {
          preAdmissionIdentifier: identifier(false),
          origin: reference(),
          admitSource: concept(),
          reAdmission: concept(),
          dischargeDisposition: concept(),
          destination: reference(),
        },
        false,
      ),
    },
    display: (fields) => join(textOf(fields, 'class'), textOf(fields, 'period')),
  },

  EpisodeOfCare: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      type: concept(true),
      patient: reference(),
      managingOrganization: reference(),
      period: period(),
      referralRequest: reference(true),
      careManager: reference(),
      team: reference(true),
      account: reference(true),
      diagnosis: group({ condition: reference(), role: concept(), rank: primitive() }),
    },
    display: statusDisplay('type'),
  },

  Flag: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      category: concept(true),
      code: concept(),
      subject: reference(),
      period: period(),
      encounter: reference(),
      author: reference(),
    },
    display: statusDisplay('code'),
  },

  List: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      mode: primitive(),
      title: primitive(),
      code: concept(),
      subject: reference(),
      encounter: reference(),
      date: primitive(),
      source: reference(),
      orderedBy: concept(),
      note: annotation(),
      emptyReason: concept(),
      entry: group({
        flag: concept(),
        deleted: primitive(),
        date: primitive(),
        item: reference(),
      }),
    },
    display: statusDisplay('title'),
  },

  Library: {
    fields: {
      identifier: identifier(),
      url: primitive(),
      version: primitive(),
      name: primitive(),
      title: primitive(),
      subtitle: primitive(),
      status: primitive(),
      experimental: primitive(),
      type: concept(),
      subject: choice(),
      date: primitive(),
      publisher: primitive(),
      contact: contact(),
      description: primitive(),
      purpose: primitive(),
      usage: primitive(),
      approvalDate: primitive(),
      lastReviewDate: primitive(),
      effectivePeriod: period(),
      topic: concept(true),
      author: contact(),
    },
    display: statusDisplay('title'),
  },
};
