import type { ResourceShape } from '../types';
import {
  annotation,
  attachment,
  choice,
  concept,
  contact,
  dataRequirement,
  group,
  identifier,
  join,
  period,
  primitive,
  quantity,
  range,
  ratio,
  reference,
  relatedArtifact,
  statusDisplay,
  textOf,
} from './helpers';

/** Backbone shared by MedicationAdministration, MedicationDispense, and Procedure. */
const performerGroup = group({
  function: concept(),
  actor: reference(),
  onBehalfOf: reference(),
});

const dosageGroup = group({
  text: primitive(),
  timing: primitive(),
  route: concept(),
  site: concept(),
  method: concept(),
  dose: choice(),
  asNeeded: choice(),
});

/**
 * Every resource in the Clinical section of the FHIR resource list.
 *
 * R4 is the canonical target, so R4 element names lead. Where a release
 * renamed the resource itself, both names are declared, since a payload can
 * arrive as either and the cross-version stage does not rename resource types
 * beyond the few in `RESOURCE_TYPE_RENAME`.
 *
 * Curated, and deliberately conservative: only elements confirmed to exist in
 * the release are declared. An element that is missed shows up in `unmapped`
 * rather than being lost, so a gap degrades into a visible report instead of
 * silent data loss.
 */
export const CLINICAL_SHAPE: Readonly<Record<string, ResourceShape>> = {
  // ------------------------------------------------------------ Summary ----
  AllergyIntolerance: {
    fields: {
      identifier: identifier(),
      clinicalStatus: concept(),
      verificationStatus: concept(),
      type: primitive(),
      category: primitive(true),
      criticality: primitive(),
      code: concept(),
      patient: reference(),
      encounter: reference(),
      onset: choice(['dateTime', 'Age', 'Period', 'Range', 'string']),
      recordedDate: primitive(),
      recorder: reference(),
      asserter: reference(),
      lastOccurrence: primitive(),
      note: annotation(),
      reaction: group({
        substance: concept(),
        manifestation: concept(true),
        description: primitive(),
        onset: primitive(),
        severity: primitive(),
        exposureRoute: concept(),
        note: annotation(),
      }),
    },
    display: (fields) => join(textOf(fields, 'code'), textOf(fields, 'criticality')),
  },

  AdverseEvent: {
    fields: {
      identifier: identifier(false),
      actuality: primitive(),
      category: concept(true),
      event: concept(),
      subject: reference(),
      encounter: reference(),
      date: primitive(),
      detected: primitive(),
      recordedDate: primitive(),
      resultingCondition: reference(true),
      location: reference(),
      seriousness: concept(),
      severity: concept(),
      outcome: concept(),
      recorder: reference(),
      contributor: reference(true),
      suspectEntity: group({ instance: reference(), causality: primitive(true) }),
      subjectMedicalHistory: reference(true),
      referenceDocument: reference(true),
      study: reference(true),
    },
    display: (fields) =>
      join(textOf(fields, 'event') ?? textOf(fields, 'code'), textOf(fields, 'actuality')),
  },

  Condition: {
    fields: {
      identifier: identifier(),
      clinicalStatus: concept(),
      verificationStatus: concept(),
      category: concept(true),
      severity: concept(),
      code: concept(),
      bodySite: concept(true),
      subject: reference(),
      encounter: reference(),
      onset: choice(['dateTime', 'Age', 'Period', 'Range', 'string']),
      abatement: choice(['dateTime', 'Age', 'Period', 'Range', 'string']),
      recordedDate: primitive(),
      recorder: reference(),
      asserter: reference(),
      note: annotation(),
      stage: group({ summary: concept(), assessment: reference(true), type: concept() }),
      evidence: group({ code: concept(true), detail: reference(true) }),
    },
    display: (fields) => join(textOf(fields, 'code'), textOf(fields, 'clinicalStatus')),
  },

  Procedure: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      statusReason: concept(),
      category: concept(),
      code: concept(),
      subject: reference(),
      encounter: reference(),
      performed: choice(['dateTime', 'Period', 'string', 'Age', 'Range']),
      recorder: reference(),
      asserter: reference(),
      performer: performerGroup,
      location: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      bodySite: concept(true),
      outcome: concept(),
      report: reference(true),
      complication: concept(true),
      followUp: concept(true),
      note: annotation(),
      usedCode: concept(true),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
      basedOn: reference(true),
      partOf: reference(true),
      complicationDetail: reference(true),
      focalDevice: group({ action: concept(), manipulated: reference() }),
      usedReference: reference(true),
    },
    display: (fields) => join(textOf(fields, 'code'), textOf(fields, 'performed')),
  },

  FamilyMemberHistory: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      dataAbsentReason: concept(),
      patient: reference(),
      date: primitive(),
      name: primitive(),
      relationship: concept(),
      sex: concept(),
      born: choice(['Period', 'date', 'string']),
      age: choice(['Age', 'Range', 'string']),
      estimatedAge: primitive(),
      deceased: choice(['boolean', 'Age', 'Range', 'date', 'string']),
      reasonCode: concept(true),
      reasonReference: reference(true),
      note: annotation(),
      condition: group({
        code: concept(),
        outcome: concept(),
        contributedToDeath: primitive(),
        onset: choice(['Age', 'Range', 'Period', 'string']),
        note: annotation(),
      }),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
    },
    display: (fields) => join(textOf(fields, 'relationship'), textOf(fields, 'name')),
  },

  DetectedIssue: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      code: concept(),
      severity: primitive(),
      patient: reference(),
      identified: choice(['dateTime', 'Period']),
      author: reference(),
      implicated: reference(true),
      detail: primitive(),
      reference: primitive(),
      mitigation: group({ action: concept(), date: primitive(), author: reference() }),
      evidence: group({ code: concept(true), detail: reference(true) }),
    },
    display: (fields) => join(textOf(fields, 'code'), textOf(fields, 'severity')),
  },

  ClinicalImpression: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      statusReason: concept(),
      code: concept(),
      description: primitive(),
      subject: reference(),
      encounter: reference(),
      effective: choice(['dateTime', 'Period']),
      date: primitive(),
      assessor: reference(),
      previous: reference(),
      problem: reference(true),
      summary: primitive(),
      prognosisCodeableConcept: concept(true),
      prognosisReference: reference(true),
      supportingInfo: reference(true),
      note: annotation(),
      finding: group({
        itemCodeableConcept: concept(),
        itemReference: reference(),
        basis: primitive(),
      }),
      investigation: group({ code: concept(), item: reference(true) }),
      protocol: primitive(true),
    },
    display: statusDisplay('code'),
  },

  // -------------------------------------------------------- Diagnostics ----
  Observation: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      category: concept(true),
      code: concept(),
      subject: reference(),
      focus: reference(true),
      encounter: reference(),
      effective: choice(['dateTime', 'Period', 'Timing', 'instant']),
      issued: primitive(),
      performer: reference(true),
      value: choice([
        'Quantity',
        'CodeableConcept',
        'string',
        'boolean',
        'integer',
        'Range',
        'Ratio',
        'SampledData',
        'time',
        'dateTime',
        'Period',
      ]),
      dataAbsentReason: concept(),
      interpretation: concept(true),
      bodySite: concept(),
      method: concept(),
      specimen: reference(),
      device: reference(),
      hasMember: reference(true),
      derivedFrom: reference(true),
      note: annotation(),
      referenceRange: group({
        low: quantity(),
        high: quantity(),
        type: concept(),
        appliesTo: concept(true),
        age: range(),
        text: primitive(),
      }),
      component: group({
        code: concept(),
        value: choice([
          'Quantity',
          'CodeableConcept',
          'string',
          'boolean',
          'integer',
          'Range',
          'Ratio',
          'SampledData',
          'time',
          'dateTime',
          'Period',
        ]),
        dataAbsentReason: concept(),
        interpretation: concept(true),
        referenceRange: group({ low: quantity(), high: quantity(), text: primitive() }),
      }),
      basedOn: reference(true),
      partOf: reference(true),
    },
    display: (fields) => join(textOf(fields, 'code'), textOf(fields, 'value')),
  },

  DiagnosticReport: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      category: concept(true),
      code: concept(),
      subject: reference(),
      encounter: reference(),
      effective: choice(['dateTime', 'Period']),
      issued: primitive(),
      performer: reference(true),
      resultsInterpreter: reference(true),
      specimen: reference(true),
      result: reference(true),
      imagingStudy: reference(true),
      conclusion: primitive(),
      conclusionCode: concept(true),
      media: group({ comment: primitive(), link: reference() }),
      basedOn: reference(true),
      presentedForm: attachment(true),
    },
    display: statusDisplay('code'),
  },

  Specimen: {
    fields: {
      identifier: identifier(),
      accessionIdentifier: identifier(false),
      status: primitive(),
      type: concept(),
      subject: reference(),
      receivedTime: primitive(),
      parent: reference(true),
      request: reference(true),
      condition: concept(true),
      note: annotation(),
      collection: group(
        {
          collector: reference(),
          collected: choice(['dateTime', 'Period']),
          duration: quantity(),
          quantity: quantity(),
          method: concept(),
          bodySite: concept(),
        },
        false,
      ),
      container: group({
        identifier: identifier(),
        description: primitive(),
        type: concept(),
        capacity: quantity(),
        specimenQuantity: quantity(),
      }),
      processing: group({
        description: primitive(),
        procedure: concept(),
        additive: reference(true),
        time: choice(['dateTime', 'Period']),
      }),
    },
    display: statusDisplay('type'),
  },

  BodyStructure: {
    fields: {
      identifier: identifier(),
      active: primitive(),
      morphology: concept(),
      location: concept(),
      locationQualifier: concept(true),
      description: primitive(),
      patient: reference(),
      image: attachment(true),
    },
    display: (fields) => join(textOf(fields, 'location'), textOf(fields, 'morphology')),
  },

  ImagingStudy: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      modality: concept(true),
      subject: reference(),
      encounter: reference(),
      started: primitive(),
      basedOn: reference(true),
      referrer: reference(),
      interpreter: reference(true),
      numberOfSeries: primitive(),
      numberOfInstances: primitive(),
      procedureReference: reference(),
      procedureCode: concept(true),
      location: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      note: annotation(),
      description: primitive(),
      series: group({
        uid: primitive(),
        number: primitive(),
        modality: concept(),
        description: primitive(),
        numberOfInstances: primitive(),
        bodySite: concept(),
        laterality: concept(),
        started: primitive(),
      }),
      endpoint: reference(true),
    },
    display: statusDisplay('description'),
  },

  /** R5 and later. R4 has no equivalent, but a migrated payload may carry it. */
  ImagingSelection: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      subject: reference(),
      issued: primitive(),
      performer: group({ function: concept(), actor: reference() }),
      basedOn: reference(true),
      category: concept(true),
      code: concept(),
      studyUid: primitive(),
      derivedFrom: reference(true),
      seriesUid: primitive(),
      seriesNumber: primitive(),
      frameOfReferenceUid: primitive(),
      bodySite: concept(),
      focus: reference(true),
    },
    display: statusDisplay('code'),
  },

  QuestionnaireResponse: {
    fields: {
      identifier: identifier(false),
      basedOn: reference(true),
      partOf: reference(true),
      questionnaire: primitive(),
      status: primitive(),
      subject: reference(),
      encounter: reference(),
      authored: primitive(),
      author: reference(),
      source: reference(),
      item: group({
        linkId: primitive(),
        definition: primitive(),
        answer: primitive(true),
        item: primitive(true),
      }),
    },
    display: statusDisplay('questionnaire'),
  },

  MolecularSequence: {
    fields: {
      identifier: identifier(),
      type: primitive(),
      coordinateSystem: primitive(),
      patient: reference(),
      specimen: reference(),
      device: reference(),
      performer: reference(),
      quantity: quantity(),
      observedSeq: primitive(),
      readCoverage: primitive(),
      referenceSeq: group(
        {
          chromosome: concept(),
          genomeBuild: primitive(),
          orientation: primitive(),
          referenceSeqId: concept(),
          referenceSeqPointer: reference(),
          referenceSeqString: primitive(),
          strand: primitive(),
          windowStart: primitive(),
          windowEnd: primitive(),
        },
        false,
      ),
      variant: group({
        start: primitive(),
        end: primitive(),
        observedAllele: primitive(),
        referenceAllele: primitive(),
        cigar: primitive(),
        variantPointer: reference(),
      }),
      quality: group({
        type: primitive(),
        standardSequence: concept(),
        start: primitive(),
        end: primitive(),
        score: quantity(),
        method: concept(),
        truthTP: primitive(),
        queryTP: primitive(),
        truthFN: primitive(),
        queryFP: primitive(),
        gtFP: primitive(),
        precision: primitive(),
        recall: primitive(),
        fScore: primitive(),
        roc: primitive(),
      }),
      repository: group({
        type: primitive(),
        url: primitive(),
        name: primitive(),
        datasetId: primitive(),
        variantsetId: primitive(),
        readsetId: primitive(),
      }),
      pointer: reference(true),
      structureVariant: group({
        variantType: concept(),
        exact: primitive(),
        length: primitive(),
        outer: primitive(),
        inner: primitive(),
      }),
    },
    display: (fields) => join(textOf(fields, 'type'), textOf(fields, 'coordinateSystem')),
  },

  /** R4 only; R5 folded Media into DocumentReference. */
  Media: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      partOf: reference(true),
      status: primitive(),
      type: concept(),
      modality: concept(),
      view: concept(),
      subject: reference(),
      encounter: reference(),
      created: choice(['dateTime', 'Period']),
      issued: primitive(),
      operator: reference(),
      reasonCode: concept(true),
      bodySite: concept(),
      deviceName: primitive(),
      device: reference(),
      height: primitive(),
      width: primitive(),
      frames: primitive(),
      duration: primitive(),
      content: group(
        {
          contentType: primitive(),
          url: primitive(),
          title: primitive(),
          size: primitive(),
          creation: primitive(),
        },
        false,
      ),
      note: annotation(),
    },
    display: statusDisplay('type'),
  },

  // -------------------------------------------------------- Medications ----
  MedicationRequest: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      statusReason: concept(),
      intent: primitive(),
      category: concept(true),
      priority: primitive(),
      doNotPerform: primitive(),
      medication: choice(['CodeableConcept', 'Reference']),
      subject: reference(),
      encounter: reference(),
      authoredOn: primitive(),
      requester: reference(),
      performer: reference(),
      performerType: concept(),
      recorder: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      courseOfTherapyType: concept(),
      note: annotation(),
      dosageInstruction: dosageGroup,
      dispenseRequest: group(
        {
          validityPeriod: period(),
          numberOfRepeatsAllowed: primitive(),
          quantity: quantity(),
          expectedSupplyDuration: quantity(),
          performer: reference(),
        },
        false,
      ),
      substitution: group({ allowedBoolean: primitive(), reason: concept() }, false),
      reported: choice(['boolean', 'Reference']),
      supportingInformation: reference(true),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
      basedOn: reference(true),
      groupIdentifier: identifier(false),
      insurance: reference(true),
      priorPrescription: reference(),
      detectedIssue: reference(true),
      eventHistory: reference(true),
    },
    display: statusDisplay('medication'),
  },

  MedicationAdministration: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      statusReason: concept(true),
      category: concept(),
      medication: choice(['CodeableConcept', 'Reference']),
      subject: reference(),
      context: reference(),
      effective: choice(['dateTime', 'Period']),
      performer: performerGroup,
      reasonCode: concept(true),
      reasonReference: reference(true),
      request: reference(),
      device: reference(true),
      note: annotation(),
      dosage: group(
        {
          text: primitive(),
          site: concept(),
          route: concept(),
          method: concept(),
          dose: quantity(),
          rate: choice(['Ratio', 'Quantity']),
        },
        false,
      ),
      instantiates: primitive(true),
      partOf: reference(true),
      supportingInformation: reference(true),
      eventHistory: reference(true),
    },
    display: statusDisplay('medication'),
  },

  MedicationDispense: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      statusReason: choice(['CodeableConcept', 'Reference']),
      category: concept(),
      medication: choice(['CodeableConcept', 'Reference']),
      subject: reference(),
      context: reference(),
      performer: performerGroup,
      location: reference(),
      authorizingPrescription: reference(true),
      type: concept(),
      quantity: quantity(),
      daysSupply: quantity(),
      whenPrepared: primitive(),
      whenHandedOver: primitive(),
      destination: reference(),
      receiver: reference(true),
      note: annotation(),
      dosageInstruction: dosageGroup,
      partOf: reference(true),
      supportingInformation: reference(true),
      substitution: group(
        {
          wasSubstituted: primitive(),
          type: concept(),
          reason: concept(true),
          responsibleParty: reference(true),
        },
        false,
      ),
      detectedIssue: reference(true),
      eventHistory: reference(true),
    },
    display: statusDisplay('medication'),
  },

  MedicationStatement: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      partOf: reference(true),
      status: primitive(),
      statusReason: concept(true),
      category: concept(),
      medication: choice(['CodeableConcept', 'Reference']),
      subject: reference(),
      context: reference(),
      effective: choice(['dateTime', 'Period']),
      dateAsserted: primitive(),
      informationSource: reference(),
      derivedFrom: reference(true),
      reasonCode: concept(true),
      reasonReference: reference(true),
      note: annotation(),
      dosage: dosageGroup,
    },
    display: statusDisplay('medication'),
  },

  Medication: {
    fields: {
      identifier: identifier(),
      code: concept(),
      status: primitive(),
      manufacturer: reference(),
      form: concept(),
      amount: ratio(),
      ingredient: group({
        itemCodeableConcept: concept(),
        itemReference: reference(),
        isActive: primitive(),
        strength: ratio(),
      }),
      batch: group({ lotNumber: primitive(), expirationDate: primitive() }, false),
    },
    display: statusDisplay('code'),
  },

  MedicationKnowledge: {
    fields: {
      code: concept(),
      status: primitive(),
      manufacturer: reference(),
      doseForm: concept(),
      amount: quantity(),
      synonym: primitive(true),
      productType: concept(true),
      intendedRoute: concept(true),
      preparationInstruction: primitive(),
      relatedMedicationKnowledge: group({ type: concept(), reference: reference(true) }),
      associatedMedication: reference(true),
      monograph: group({ type: concept(), source: reference() }),
      ingredient: group({
        item: choice(['CodeableConcept', 'Reference']),
        isActive: primitive(),
        strength: ratio(),
      }),
      cost: group({ type: concept(), source: primitive(), cost: quantity() }),
      monitoringProgram: group({ type: concept(), name: primitive() }),
      administrationGuidelines: group({
        dosage: primitive(true),
        indication: choice(['CodeableConcept', 'Reference']),
        patientCharacteristics: primitive(true),
      }),
      medicineClassification: group({ type: concept(), classification: concept(true) }),
      packaging: group({ type: concept(), quantity: quantity() }, false),
      drugCharacteristic: group({
        type: concept(),
        value: choice(['CodeableConcept', 'string', 'Quantity', 'base64Binary']),
      }),
      contraindication: reference(true),
      regulatory: group({
        regulatoryAuthority: reference(),
        substitution: primitive(true),
        schedule: primitive(true),
        maxDispense: primitive(),
      }),
      kinetics: group({
        areaUnderCurve: quantity(true),
        lethalDose50: quantity(true),
        halfLifePeriod: quantity(),
      }),
    },
    display: statusDisplay('code'),
  },

  Immunization: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      statusReason: concept(),
      vaccineCode: concept(),
      patient: reference(),
      encounter: reference(),
      occurrence: choice(['dateTime', 'string']),
      recorded: primitive(),
      primarySource: primitive(),
      reportOrigin: concept(),
      location: reference(),
      manufacturer: reference(),
      lotNumber: primitive(),
      expirationDate: primitive(),
      site: concept(),
      route: concept(),
      doseQuantity: quantity(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      isSubpotent: primitive(),
      note: annotation(),
      performer: group({ function: concept(), actor: reference() }),
      protocolApplied: group({
        series: primitive(),
        authority: reference(),
        targetDisease: concept(true),
        doseNumber: choice(['positiveInt', 'string']),
        seriesDoses: choice(['positiveInt', 'string']),
      }),
      subpotentReason: concept(true),
      education: group({
        documentType: primitive(),
        reference: primitive(),
        publicationDate: primitive(),
        presentationDate: primitive(),
      }),
      programEligibility: concept(true),
      fundingSource: concept(),
      reaction: group({ date: primitive(), detail: reference(), reported: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'vaccineCode'), textOf(fields, 'occurrence')),
  },

  ImmunizationEvaluation: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      patient: reference(),
      date: primitive(),
      authority: reference(),
      targetDisease: concept(),
      immunizationEvent: reference(),
      doseStatus: concept(),
      doseStatusReason: concept(true),
      description: primitive(),
      series: primitive(),
      doseNumber: choice(['positiveInt', 'string']),
      seriesDoses: choice(['positiveInt', 'string']),
    },
    display: (fields) => join(textOf(fields, 'targetDisease'), textOf(fields, 'doseStatus')),
  },

  ImmunizationRecommendation: {
    fields: {
      identifier: identifier(),
      patient: reference(),
      date: primitive(),
      authority: reference(),
      recommendation: group({
        vaccineCode: concept(true),
        targetDisease: concept(),
        contraindicatedVaccineCode: concept(true),
        forecastStatus: concept(),
        forecastReason: concept(true),
        description: primitive(),
        series: primitive(),
        doseNumber: choice(['positiveInt', 'string']),
        seriesDoses: choice(['positiveInt', 'string']),
      }),
    },
    display: (fields) => textOf(fields, 'date'),
  },

  // ----------------------------------------------------- Care Provision ----
  CarePlan: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      replaces: reference(true),
      partOf: reference(true),
      status: primitive(),
      intent: primitive(),
      category: concept(true),
      title: primitive(),
      description: primitive(),
      subject: reference(),
      encounter: reference(),
      period: period(),
      created: primitive(),
      author: reference(),
      contributor: reference(true),
      careTeam: reference(true),
      addresses: reference(true),
      supportingInfo: reference(true),
      goal: reference(true),
      note: annotation(),
      activity: group({
        outcomeCodeableConcept: concept(true),
        outcomeReference: reference(true),
        reference: reference(),
        progress: annotation(),
      }),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
    },
    display: statusDisplay('title'),
  },

  CareTeam: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      category: concept(true),
      name: primitive(),
      subject: reference(),
      encounter: reference(),
      period: period(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      managingOrganization: reference(true),
      telecom: contact(),
      note: annotation(),
      participant: group({
        role: concept(true),
        member: reference(),
        onBehalfOf: reference(),
        period: period(),
      }),
    },
    display: statusDisplay('name'),
  },

  Goal: {
    fields: {
      identifier: identifier(),
      lifecycleStatus: primitive(),
      achievementStatus: concept(),
      category: concept(true),
      priority: concept(),
      description: concept(),
      subject: reference(),
      start: choice(['date', 'CodeableConcept']),
      statusDate: primitive(),
      statusReason: primitive(),
      expressedBy: reference(),
      addresses: reference(true),
      note: annotation(),
      outcomeCode: concept(true),
      outcomeReference: reference(true),
      target: group({
        measure: concept(),
        detail: choice([
          'Quantity',
          'Range',
          'CodeableConcept',
          'string',
          'boolean',
          'integer',
          'Ratio',
        ]),
        due: choice(['date', 'Duration']),
      }),
    },
    display: (fields) => join(textOf(fields, 'description'), textOf(fields, 'lifecycleStatus')),
  },

  ServiceRequest: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      replaces: reference(true),
      status: primitive(),
      intent: primitive(),
      category: concept(true),
      priority: primitive(),
      doNotPerform: primitive(),
      code: concept(),
      orderDetail: concept(true),
      quantity: choice(['Quantity', 'Ratio', 'Range']),
      subject: reference(),
      encounter: reference(),
      occurrence: choice(['dateTime', 'Period', 'Timing']),
      asNeeded: choice(['boolean', 'CodeableConcept']),
      authoredOn: primitive(),
      requester: reference(),
      performerType: concept(),
      performer: reference(true),
      locationCode: concept(true),
      locationReference: reference(true),
      reasonCode: concept(true),
      reasonReference: reference(true),
      specimen: reference(true),
      bodySite: concept(true),
      note: annotation(),
      patientInstruction: primitive(),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
      requisition: identifier(false),
      insurance: reference(true),
      supportingInfo: reference(true),
      relevantHistory: reference(true),
    },
    display: statusDisplay('code'),
  },

  NutritionOrder: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      intent: primitive(),
      patient: reference(),
      encounter: reference(),
      dateTime: primitive(),
      orderer: reference(),
      allergyIntolerance: reference(true),
      foodPreferenceModifier: concept(true),
      excludeFoodModifier: concept(true),
      note: annotation(),
      oralDiet: group({ type: concept(true), instruction: primitive() }, false),
      supplement: group({ type: concept(), productName: primitive(), quantity: quantity() }),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
      instantiates: primitive(true),
      enteralFormula: group(
        {
          baseFormulaType: concept(),
          baseFormulaProductName: primitive(),
          additiveType: concept(),
          additiveProductName: primitive(),
          caloricDensity: quantity(),
          routeofAdministration: concept(),
          administration: primitive(true),
          maxVolumeToDeliver: quantity(),
          administrationInstruction: primitive(),
        },
        false,
      ),
    },
    display: (fields) => join(textOf(fields, 'status'), textOf(fields, 'dateTime')),
  },

  /** R5 and later. */
  NutritionIntake: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      statusReason: concept(true),
      code: concept(),
      subject: reference(),
      encounter: reference(),
      occurrence: choice(),
      recorded: primitive(),
      reported: choice(),
      location: reference(),
      note: annotation(),
      consumedItem: group({
        type: concept(),
        nutritionProduct: concept(),
        amount: quantity(),
        notConsumed: primitive(),
      }),
    },
    display: statusDisplay('code'),
  },

  VisionPrescription: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      created: primitive(),
      patient: reference(),
      encounter: reference(),
      dateWritten: primitive(),
      prescriber: reference(),
      lensSpecification: group({
        product: concept(),
        eye: primitive(),
        sphere: primitive(),
        cylinder: primitive(),
        axis: primitive(),
        add: primitive(),
        power: primitive(),
        note: annotation(),
      }),
    },
    display: (fields) => join(textOf(fields, 'status'), textOf(fields, 'dateWritten')),
  },

  RiskAssessment: {
    fields: {
      identifier: identifier(),
      basedOn: reference(),
      parent: reference(),
      status: primitive(),
      method: concept(),
      code: concept(),
      subject: reference(),
      encounter: reference(),
      occurrence: choice(['dateTime', 'Period']),
      condition: reference(),
      performer: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      basis: reference(true),
      mitigation: primitive(),
      note: annotation(),
      prediction: group({
        outcome: concept(),
        probability: choice(['decimal', 'Range']),
        qualitativeRisk: concept(),
        relativeRisk: primitive(),
        when: choice(['Period', 'Range']),
        rationale: primitive(),
      }),
    },
    display: statusDisplay('code'),
  },

  RequestGroup: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      replaces: reference(true),
      status: primitive(),
      intent: primitive(),
      priority: primitive(),
      code: concept(),
      subject: reference(),
      encounter: reference(),
      authoredOn: primitive(),
      author: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      note: annotation(),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
      groupIdentifier: identifier(false),
      action: group({
        prefix: primitive(),
        title: primitive(),
        description: primitive(),
        textEquivalent: primitive(),
        priority: primitive(),
        code: concept(true),
        documentation: relatedArtifact(),
        condition: primitive(true),
        relatedAction: primitive(true),
        timing: choice(['dateTime', 'Age', 'Period', 'Duration', 'Range', 'Timing']),
        participant: reference(true),
        type: concept(),
        groupingBehavior: primitive(),
        selectionBehavior: primitive(),
        requiredBehavior: primitive(),
        precheckBehavior: primitive(),
        cardinalityBehavior: primitive(),
        resource: reference(),
        action: primitive(true),
      }),
    },
    display: statusDisplay('code'),
  },

  // ---------------------------------------------------- Request/Response ----
  Communication: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      partOf: reference(true),
      inResponseTo: reference(true),
      status: primitive(),
      statusReason: concept(),
      category: concept(true),
      priority: primitive(),
      medium: concept(true),
      subject: reference(),
      topic: concept(),
      about: reference(true),
      encounter: reference(),
      sent: primitive(),
      received: primitive(),
      recipient: reference(true),
      sender: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      note: annotation(),
      payload: group({ contentString: primitive(), contentReference: reference() }),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
    },
    display: statusDisplay('category'),
  },

  CommunicationRequest: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      replaces: reference(true),
      status: primitive(),
      statusReason: concept(),
      category: concept(true),
      priority: primitive(),
      doNotPerform: primitive(),
      medium: concept(true),
      subject: reference(),
      about: reference(true),
      encounter: reference(),
      occurrence: choice(['dateTime', 'Period']),
      authoredOn: primitive(),
      requester: reference(),
      recipient: reference(true),
      sender: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      note: annotation(),
      payload: group({ contentString: primitive(), contentReference: reference() }),
      groupIdentifier: identifier(false),
    },
    display: statusDisplay('category'),
  },

  DeviceRequest: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      priorRequest: reference(true),
      status: primitive(),
      intent: primitive(),
      priority: primitive(),
      code: choice(['Reference', 'CodeableConcept']),
      subject: reference(),
      encounter: reference(),
      occurrence: choice(['dateTime', 'Period', 'Timing']),
      authoredOn: primitive(),
      requester: reference(),
      performerType: concept(),
      performer: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      note: annotation(),
      instantiatesCanonical: primitive(true),
      instantiatesUri: primitive(true),
      groupIdentifier: identifier(false),
      parameter: group({
        code: concept(),
        value: choice(['CodeableConcept', 'Quantity', 'Range', 'boolean']),
      }),
      insurance: reference(true),
      supportingInfo: reference(true),
      relevantHistory: reference(true),
    },
    display: statusDisplay('code'),
  },

  /** R4 name; R5 renamed it DeviceUsage, R6 DeviceAssociation. */
  DeviceUseStatement: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      status: primitive(),
      subject: reference(),
      derivedFrom: reference(true),
      timing: choice(['Timing', 'Period', 'dateTime']),
      recordedOn: primitive(),
      source: reference(),
      device: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      bodySite: concept(),
      note: annotation(),
    },
    display: statusDisplay('device'),
  },

  GuidanceResponse: {
    fields: {
      requestIdentifier: identifier(false),
      identifier: identifier(),
      module: choice(['uri', 'canonical', 'CodeableConcept']),
      status: primitive(),
      subject: reference(),
      encounter: reference(),
      occurrenceDateTime: primitive(),
      performer: reference(),
      reasonCode: concept(true),
      reasonReference: reference(true),
      note: annotation(),
      evaluationMessage: reference(true),
      outputParameters: reference(),
      result: reference(),
      dataRequirement: dataRequirement(),
    },
    display: (fields) => join(textOf(fields, 'module'), textOf(fields, 'status')),
  },

  SupplyRequest: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      category: concept(),
      priority: primitive(),
      item: choice(['CodeableConcept', 'Reference']),
      quantity: quantity(),
      occurrence: choice(['dateTime', 'Period', 'Timing']),
      authoredOn: primitive(),
      requester: reference(),
      supplier: reference(true),
      reasonCode: concept(true),
      reasonReference: reference(true),
      deliverFrom: reference(),
      deliverTo: reference(),
      parameter: group({
        code: concept(),
        value: choice(['CodeableConcept', 'Quantity', 'Range', 'boolean']),
      }),
    },
    display: statusDisplay('item'),
  },

  SupplyDelivery: {
    fields: {
      identifier: identifier(),
      basedOn: reference(true),
      partOf: reference(true),
      status: primitive(),
      patient: reference(),
      type: concept(),
      occurrence: choice(['dateTime', 'Period', 'Timing']),
      supplier: reference(),
      destination: reference(),
      receiver: reference(true),
      suppliedItem: group(
        { quantity: quantity(), item: choice(['CodeableConcept', 'Reference']) },
        false,
      ),
    },
    display: statusDisplay('type'),
  },
};

/**
 * Resource types renamed across releases. Both names map to the same shape, so
 * an R5 or R6 payload that survives the cross-version stage still normalizes.
 */
export const CLINICAL_ALIAS: Readonly<Record<string, string>> = {
  DeviceUsage: 'DeviceUseStatement',
  DeviceAssociation: 'DeviceUseStatement',
  RequestOrchestration: 'RequestGroup',
};
