import type { ResourceShape } from '../types';
import {
  annotation,
  choice,
  concept,
  contact,
  group,
  identifier,
  join,
  period,
  primitive,
  quantity,
  reference,
  statusDisplay,
  textOf,
} from './helpers';

/** Money is a Quantity-shaped datatype: `{ value, currency }`. */
const money = () => quantity();

/** Claim, ClaimResponse, and ExplanationOfBenefit all carry adjudications. */
const adjudicationGroup = group({
  category: concept(),
  reason: concept(),
  amount: money(),
  value: primitive(),
});

/**
 * Every resource in the Financial section of the FHIR resource list —
 * Support, Billing, Payment, and General.
 *
 * R4 element names lead, since R4 is the canonical target, and the R4 members
 * the current build dropped or moved are covered too. These resources are
 * unusually deep — an ExplanationOfBenefit has dozens of backbone elements —
 * so the shapes declare the fields that identify and summarise a record rather
 * than every line-item detail. Anything undeclared is still read generically
 * and reported in `unmapped`.
 */
export const FINANCIAL_SHAPE: Readonly<Record<string, ResourceShape>> = {
  // ------------------------------------------------------------ Support ----
  Coverage: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      type: concept(),
      policyHolder: reference(),
      subscriber: reference(),
      subscriberId: primitive(),
      beneficiary: reference(),
      dependent: primitive(),
      relationship: concept(),
      period: period(),
      payor: reference(true),
      order: primitive(),
      network: primitive(),
      subrogation: primitive(),
      contract: reference(true),
      class: group({ type: concept(), value: primitive(), name: primitive() }),
      costToBeneficiary: group({ type: concept(), value: choice() }),
    },
    display: statusDisplay('type'),
  },

  CoverageEligibilityRequest: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      priority: concept(),
      purpose: primitive(true),
      patient: reference(),
      serviced: choice(),
      created: primitive(),
      enterer: reference(),
      provider: reference(),
      insurer: reference(),
      facility: reference(),
      insurance: group({
        focal: primitive(),
        coverage: reference(),
        businessArrangement: primitive(),
      }),
      item: group({ category: concept(), productOrService: concept(), quantity: quantity() }),
    },
    display: statusDisplay('priority'),
  },

  CoverageEligibilityResponse: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      purpose: primitive(true),
      patient: reference(),
      serviced: choice(),
      created: primitive(),
      requestor: reference(),
      request: reference(),
      outcome: primitive(),
      disposition: primitive(),
      insurer: reference(),
      preAuthRef: primitive(),
      form: concept(),
      insurance: group({ coverage: reference(), inforce: primitive(), benefitPeriod: period() }),
      error: group({ code: concept() }),
    },
    display: (fields) => join(textOf(fields, 'outcome'), textOf(fields, 'status')),
  },

  // ------------------------------------------------------------ Billing ----
  Claim: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      type: concept(),
      subType: concept(),
      use: primitive(),
      patient: reference(),
      billablePeriod: period(),
      created: primitive(),
      enterer: reference(),
      insurer: reference(),
      provider: reference(),
      priority: concept(),
      fundsReserve: concept(),
      prescription: reference(),
      payee: group({ type: concept(), party: reference() }, false),
      referral: reference(),
      facility: reference(),
      total: money(),
      careTeam: group({ sequence: primitive(), provider: reference(), role: concept() }),
      diagnosis: group({ sequence: primitive(), diagnosis: choice(), type: concept(true) }),
      procedure: group({ sequence: primitive(), procedure: choice(), date: primitive() }),
      insurance: group({ sequence: primitive(), focal: primitive(), coverage: reference() }),
      accident: group({ date: primitive(), type: concept(), location: choice() }, false),
      item: group({
        sequence: primitive(),
        productOrService: concept(),
        serviced: choice(),
        quantity: quantity(),
        unitPrice: money(),
        net: money(),
      }),
    },
    display: statusDisplay('type'),
  },

  ClaimResponse: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      type: concept(),
      subType: concept(),
      use: primitive(),
      patient: reference(),
      created: primitive(),
      insurer: reference(),
      requestor: reference(),
      request: reference(),
      outcome: primitive(),
      disposition: primitive(),
      preAuthRef: primitive(),
      preAuthPeriod: period(),
      payeeType: concept(),
      formCode: concept(),
      payment: group(
        { type: concept(), amount: money(), date: primitive(), adjustment: money() },
        false,
      ),
      total: group({ category: concept(), amount: money() }),
      item: group({ itemSequence: primitive(), adjudication: adjudicationGroup }),
      error: group({ code: concept() }),
      processNote: group({ number: primitive(), type: primitive(), text: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'outcome'), textOf(fields, 'status')),
  },

  // ------------------------------------------------------------ Payment ----
  PaymentNotice: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      request: reference(),
      response: reference(),
      created: primitive(),
      provider: reference(),
      payment: reference(),
      paymentDate: primitive(),
      payee: reference(),
      recipient: reference(),
      amount: money(),
      paymentStatus: concept(),
    },
    display: (fields) => join(textOf(fields, 'amount'), textOf(fields, 'status')),
  },

  PaymentReconciliation: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      period: period(),
      created: primitive(),
      paymentIssuer: reference(),
      request: reference(),
      requestor: reference(),
      outcome: primitive(),
      disposition: primitive(),
      paymentDate: primitive(),
      paymentAmount: money(),
      paymentIdentifier: identifier(false),
      formCode: concept(),
      detail: group({
        identifier: identifier(false),
        type: concept(),
        request: reference(),
        submitter: reference(),
        payee: reference(),
        date: primitive(),
        amount: money(),
      }),
      processNote: group({ type: primitive(), text: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'paymentAmount'), textOf(fields, 'status')),
  },

  // ------------------------------------------------------------ General ----
  Account: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      type: concept(),
      name: primitive(),
      subject: reference(true),
      servicePeriod: period(),
      owner: reference(),
      description: primitive(),
      partOf: reference(),
      coverage: group({ coverage: reference(), priority: primitive() }),
      guarantor: group({ party: reference(), onHold: primitive(), period: period() }),
    },
    display: statusDisplay('name'),
  },

  ExplanationOfBenefit: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      type: concept(),
      subType: concept(),
      use: primitive(),
      patient: reference(),
      billablePeriod: period(),
      created: primitive(),
      enterer: reference(),
      insurer: reference(),
      provider: reference(),
      priority: concept(),
      claim: reference(),
      claimResponse: reference(),
      outcome: primitive(),
      disposition: primitive(),
      referral: reference(),
      facility: reference(),
      precedence: primitive(),
      formCode: concept(),
      benefitPeriod: period(),
      payee: group({ type: concept(), party: reference() }, false),
      payment: group({ type: concept(), amount: money(), date: primitive() }, false),
      careTeam: group({ sequence: primitive(), provider: reference(), role: concept() }),
      diagnosis: group({ sequence: primitive(), diagnosis: choice(), type: concept(true) }),
      insurance: group({ focal: primitive(), coverage: reference() }),
      total: group({ category: concept(), amount: money() }),
      item: group({
        sequence: primitive(),
        productOrService: concept(),
        serviced: choice(),
        quantity: quantity(),
        unitPrice: money(),
        net: money(),
        adjudication: adjudicationGroup,
      }),
      benefitBalance: group({
        category: concept(),
        excluded: primitive(),
        name: primitive(),
        description: primitive(),
        network: concept(),
        unit: concept(),
        term: concept(),
      }),
      processNote: group({ number: primitive(), type: primitive(), text: primitive() }),
    },
    display: (fields) => join(textOf(fields, 'type'), textOf(fields, 'outcome')),
  },

  // -------------------------------------------- R4 members not in the build ----
  EnrollmentRequest: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      created: primitive(),
      insurer: reference(),
      provider: reference(),
      candidate: reference(),
      coverage: reference(),
    },
    display: (fields) => join(textOf(fields, 'status'), textOf(fields, 'created')),
  },

  EnrollmentResponse: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      request: reference(),
      outcome: primitive(),
      disposition: primitive(),
      created: primitive(),
      organization: reference(),
      requestProvider: reference(),
    },
    display: (fields) => join(textOf(fields, 'outcome'), textOf(fields, 'status')),
  },

  Invoice: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      cancelledReason: primitive(),
      type: concept(),
      subject: reference(),
      recipient: reference(),
      date: primitive(),
      issuer: reference(),
      account: reference(),
      totalNet: money(),
      totalGross: money(),
      paymentTerms: primitive(),
      note: annotation(),
      participant: group({ role: concept(), actor: reference() }),
      lineItem: group({ sequence: primitive(), chargeItem: choice() }),
    },
    display: (fields) => join(textOf(fields, 'totalGross'), textOf(fields, 'status')),
  },

  ChargeItem: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      code: concept(),
      subject: reference(),
      context: reference(),
      occurrence: choice(),
      performingOrganization: reference(),
      requestingOrganization: reference(),
      costCenter: reference(),
      quantity: quantity(),
      // Lowercase `s` is the spec's own spelling on this resource.
      bodysite: concept(true),
      factorOverride: primitive(),
      priceOverride: money(),
      overrideReason: primitive(),
      enterer: reference(),
      enteredDate: primitive(),
      reason: concept(true),
      service: reference(true),
      account: reference(true),
      note: annotation(),
      performer: group({ function: concept(), actor: reference() }),
    },
    display: statusDisplay('code'),
  },

  ChargeItemDefinition: {
    fields: {
      url: primitive(),
      identifier: identifier(),
      version: primitive(),
      title: primitive(),
      status: primitive(),
      experimental: primitive(),
      date: primitive(),
      publisher: primitive(),
      contact: contact(),
      description: primitive(),
      copyright: primitive(),
      approvalDate: primitive(),
      lastReviewDate: primitive(),
      effectivePeriod: period(),
      code: concept(),
      instance: reference(true),
    },
    display: statusDisplay('title'),
  },

  Contract: {
    fields: {
      identifier: identifier(),
      url: primitive(),
      version: primitive(),
      status: primitive(),
      legalState: concept(),
      contentDerivative: concept(),
      issued: primitive(),
      applies: period(),
      expirationType: concept(),
      subject: reference(true),
      authority: reference(true),
      domain: reference(true),
      site: reference(true),
      name: primitive(),
      title: primitive(),
      subtitle: primitive(),
      alias: primitive(true),
      author: reference(),
      scope: concept(),
      topic: choice(),
      type: concept(),
      subType: concept(true),
      signer: group({ type: concept(), party: reference() }),
    },
    display: statusDisplay('title'),
  },

  InsurancePlan: {
    fields: {
      identifier: identifier(),
      status: primitive(),
      type: concept(true),
      name: primitive(),
      alias: primitive(true),
      period: period(),
      ownedBy: reference(),
      administeredBy: reference(),
      coverageArea: reference(true),
      endpoint: reference(true),
      network: reference(true),
      contact: group({ purpose: concept(), telecom: contact() }),
      coverage: group({ type: concept(), network: reference(true) }),
      plan: group({ type: concept(), coverageArea: reference(true), network: reference(true) }),
    },
    display: statusDisplay('name'),
  },
};
